### ISSUE TITLE
Error when upgrading rspack v0.2.12 -> v0.3.0

### ISSUE THREAD

**Issue by rodrigofariow** [th3fallen/cypress-rspack-dev-server#8] opened 2023-08-24 18:09 UTC
Hi @th3fallen ,

First of all, thank you for the awesome work on this dev server adptation 👍 

rspack 0.3.0 just dropped today and I tried upgrading our codebase to it.
All the builds are still working fine (dev, prod) by doing the upgrade except for cypress.
I'm suspecting 'cypress-rspack-dev-server' is the cause here but I'm not sure.

I'm leaving some details that can help clarifying.

```
node -v
v20.5.1
```

Here is my cypress config:
```
import { devServer } from 'cypress-rspack-dev-server'
import { defineConfig } from 'cypress'

export default defineConfig({
  video: false,
  component: {
    viewportWidth: 1280,
    viewportHeight: 720,
    experimentalSingleTabRunMode: true, // improves performance on cypress run (good for CI)
    experimentalMemoryManagement: true, // should solve "Out of Memory" issues
    devServer(devServerConfig) {
      return devServer({
        ...devServerConfig,
        framework: 'react',
        rspackConfig: require('./webpack.config.js'),
      })
    },
    supportFile: 'apps/fleet-web/cypress/support/component.ts',
    specPattern: 'apps/fleet-web/**/*.cy.{tsx,jsx,js,ts}',
    screenshotsFolder: 'apps/fleet-web/cypress/screenshots',
    fixturesFolder: 'apps/fleet-web/cypress/fixtures',
  },
})
```

**Here is there error when I run**
`pnpm cypress run --component --config-file ./my-config.ts`

```
Your configFile threw an error from: ./apps/fleet-web/cypress.config.ts

We stopped running your tests because your config file crashed.

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/node_modules/@rspack/core/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:261:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:591:9)
    at resolveExports (node:internal/modules/cjs/loader:547:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:621:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at Function.Module._resolveFilename (/Users/rodrigofaria/Library/Caches/Cypress/12.17.2/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/rodrigofaria/Library/Caches/Cypress/12.17.2/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at sourceRspack (/Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/node_modules/.pnpm/cypress-rspack-dev-server@0.0.2_@swc+core@1.3.78_esbuild@0.17.18_react-refresh@0.14.0_ts-node_hwoaebeaaj2i665wxo5ugl4fzq/node_modules/cypress-rspack-dev-server/dist/helpers/sourceRelativeRspackModules.js:70:34)
    at sourceDefaultRspackDependencies (/Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/node_modules/.pnpm/cypress-rspack-dev-server@0.0.2_@swc+core@1.3.78_esbuild@0.17.18_react-refresh@0.14.0_ts-node_hwoaebeaaj2i665wxo5ugl4fzq/node_modules/cypress-rspack-dev-server/dist/helpers/sourceRelativeRspackModules.js:146:21)
    at defaultRspackModules (/Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/node_modules/.pnpm/cypress-rspack-dev-server@0.0.2_@swc+core@1.3.78_esbuild@0.17.18_react-refresh@0.14.0_ts-node_hwoaebeaaj2i665wxo5ugl4fzq/node_modules/cypress-rspack-dev-server/dist/devServer.js:51:136)
    at getPreset (/Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/node_modules/.pnpm/cypress-rspack-dev-server@0.0.2_@swc+core@1.3.78_esbuild@0.17.18_react-refresh@0.14.0_ts-node_hwoaebeaaj2i665wxo5ugl4fzq/node_modules/cypress-rspack-dev-server/dist/devServer.js:72:20)
    at Function.devServer.create (/Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/node_modules/.pnpm/cypress-rspack-dev-server@0.0.2_@swc+core@1.3.78_esbuild@0.17.18_react-refresh@0.14.0_ts-node_hwoaebeaaj2i665wxo5ugl4fzq/node_modules/cypress-rspack-dev-server/dist/devServer.js:84:66)
    at /Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/node_modules/.pnpm/cypress-rspack-dev-server@0.0.2_@swc+core@1.3.78_esbuild@0.17.18_react-refresh@0.14.0_ts-node_hwoaebeaaj2i665wxo5ugl4fzq/node_modules/cypress-rspack-dev-server/dist/devServer.js:20:40
    at new Promise (<anonymous>)
    at devServer (/Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/node_modules/.pnpm/cypress-rspack-dev-server@0.0.2_@swc+core@1.3.78_esbuild@0.17.18_react-refresh@0.14.0_ts-node_hwoaebeaaj2i665wxo5ugl4fzq/node_modules/cypress-rspack-dev-server/dist/devServer.js:19:12)
    at devServer (/Users/rodrigofaria/Documents/frontend/fleetweb-wt/copy2/apps/fleet-web/cypress.config.ts:12:23)
    at Object.handler (/Users/rodrigofaria/Library/Caches/Cypress/12.17.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:177:22)
    at RunPlugins.invoke (/Users/rodrigofaria/Library/Caches/Cypress/12.17.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:183:18)
    at /Users/rodrigofaria/Library/Caches/Cypress/12.17.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/Users/rodrigofaria/Library/Caches/Cypress/12.17.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
```

I can't clearly tell what's the root cause here but hopefully you could help me understand if it has anything to do with `cypress-rspack-dev-server` or not.

Cheers!

**Comment by th3fallen** [comment] 2023-08-24 18:20
hmm, i'll take a peek and see what i can come up with. i didnt notice they'd released another update so soon (they're so damn fast)

**Comment by rodrigofariow** [comment] 2023-08-24 18:20
Much appreciated @th3fallen !

They really are 😆

**Comment by rexizam** [comment] 2023-09-14 12:03
Experiencing the same issue with @rspack/core 0.3.4

**Comment by xfsnowind** [comment] 2023-11-06 09:51
I think the problem is caused by rspack 0.3.0 which restricted to export rspack packages' `package.json`, I explained [here](https://github.com/web-infra-dev/rspack/issues/4541) and created the PR based on that. Hope it would be release early.

**Comment by th3fallen** [comment] 2023-11-14 15:11
Resolved by https://github.com/th3fallen/cypress-rspack-dev-server/pull/10

**Closed by th3fallen** 2023-11-14 15:11 UTC
